version: '3'

services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data/redis"

    mysql:
        image: "mysql:latest"
        container_name: icchannel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: icchannel_db
            MYSQL_USER: shumiya
            MYSQL_PASSWORD: shumiya
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./mysql/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    icchannel_api:
        image: zenika/kotlin:latest
        ports:
            - "8080:8080"
        working_dir: /app
        volumes:
            - "./IcchannelBackend/build/libs:/app"
        environment:
            SPRING_PROFILES_ACTIVE: production
            FRONT_ORIGIN: $FRONT_ORIGIN
            TZ: Asia/Tokyo
        command: ["java", "-jar", "IcchannelBackend-0.0.1-SNAPSHOT.war"]

    icchannel_front:
        image: node:14.15.5
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - "./icchannel_frontend:/app"
        environment:
            NEXT_PUBLIC_API_SERVER: $NEXT_PUBLIC_API_SERVER
        command: [sh, -c, yarn start]

    nginx:
        image: "nginx:latest"
        ports:
            - 80:80
            - 443:443
            - 18080:18080
        volumes:
            - ./icchannel_front/out:/var/www/html
            - ./nginx:/etc/nginx/conf.d
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - icchannel_front

    certbot:
        image: certbot/certbot:v1.7.0
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./icchannel_front/out:/var/www/html
        command: ["--version"]

